config/routes.rb
Rails.application.routes.draw do
  root to: "arts#index"
  resources :users, only: [:new, :show, :create] do
     resources :arts
  end 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
    has_one_attached :image
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :arts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  def index 
    @arts = Art.all
    @users = User.all
  end
  
  def new
    @art = Art.new
    @user = User.find(params[:user_id])
    @name = @user.name
  end

  def create
    art = Art.create(art_params) # POINT
    redirect_to "/users/#{art.user.id}"
  end

  def show
    @art = Art.find(params[:id])
  end

  def edit
    @art = Art.find_by(params[:user_id],params[:id])
    
    @user = @art.user
    @name = @user.name
  end

  def update
    art = Art.find_by(params[:user_id],params[:id])
    art.update(art_params) # POINT
    redirect_to "/"
  end
  
  def destroy
    art = Art.find_by(params[:user_id],params[:id])
    art.destroy
    redirect_to "/"
  end
  
  private 
  
  def art_params
       params.require(:art).permit(:content, :image, :grate, :title).merge(user_id: params[:user_id])
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      
      def new
        @user = User.new
      end
    
      def create
        User.create(user_params) # POINT
        redirect_to "/"
      end
      
      def show
        @user = User.find(params[:id])
        @name = @user.name
        @arts = @user.arts
      end
      
      
      private 
      
      def user_params
           params.require(:user).permit(:name)
      end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/arts/edit.html.erb
<header class="header">
    <div class="header_title"><a href="/">こども作品保存箱</a></div>
    <div class="header_right">
        <div class="top_back"><a href="/">top page</a></div>
    </div>
</header>


<div class="container">
    <div class="art_container">
        <h2 class="sub_title">
    <%= "#{@name}の作品編集" %>
        </h2>
        <%= form_with(model: [@user, @art], local: true) do |form| %>
          <%= form.text_field :title, placeholder: "タイトル", class: "art_title" %><br>
          <%= form.file_field :image, class: "art_image" %><br>
          <div class="art_grate_grid">
           <%= form.text_field :grate, placeholder: "学年", class: "art_grate" %>年生　作成<br>
          </div>
          <%= form.text_area :content, placeholder: "コメント",class: "art_content" %><br>
          <div class="art_btn_grit">
            <%= form.submit "編集", class: "art_btn" %>
          </div>
    <% end %>
    </div>
</div>

app/views/arts/index.html.erb
<header class="header">
    <div class="header_title"><a href="/">こども作品保存箱</a></div>
    <div class="header_right">
        <%= link_to "name ently", new_user_path, class: "name_ently" %>
        
        <div class="name_select">name select
           <div class="name_list_box">
            <% @users.each do |user|  %>
                <div class="name_list hedden">
                   <%= link_to "#{user.name}", user_path(user.id) %>
                </div>
            <% end %>
           </div>
        </div>
    </div>
</header>

<div class="contents">
    <div class="boxs">
        <% @arts.each do |art| %>
        <div class="art_box">
            <div class="art_left">
                <div class="left_title">
                    <%= art.title %>
                </div>
               
            </div>
            <div class="art_right">
                <%= image_tag art.image %>
            </div>
        </div>
        <% end %>
    </div>

    
</div>

app/views/arts/new.html.erb
<header class="header">
    <div class="header_title"><a href="/">こども作品保存箱</a></div>
    <div class="header_right">
        <div class="top_back"><a href="/">トップページへ</a></div>
    </div>
</header>

<h1>作品投稿</h1>
<%= form_with(model: [@user, @art], local: true) do |form| %>
  <%= form.text_field :title %><br>
  <%= form.file_field :image %><br>
  <%= form.text_field :grate %><br>
  <%= form.text_area :content %><br>
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtBox3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<header class="header">
    <div class="header_title"><a href="/">こども作品保存箱</a></div>
    <div class="header_right">
        <div class="top_back"><a href="/">top page</a></div>
    </div>
</header>

<div class="container">
    <div class="ently_container">
        <h2 class="sub_title">おなまえ登録</h2>
         <%= form_with(model: @user, local: true) do |form| %>
            <%= form.text_field :name, placeholder: "タロウ", class: "ently_name" %>
            <div class="ently_btn_box">
              <%= form.submit "登録", class: "ently_btn" %>
            </div>
        <% end %>
       
    </div>
    
    
</div>

app/views/users/show.html.erb
<header class="header">
    <div class="header_title"><a href="/">こども作品保存箱</a></div>
    <div class="header_right">
        <div class="top_back"><a href="/">top page</a></div>
    </div>
</header>

<div class="contents">
    <div class="new_art_box">
         <div class="box_title">🌼<%= @name %>の作品集🌼</div>
         <div class="art_new">
           <%= link_to "作品 登録 ボタン", new_user_art_path(@user.id) %>
         </div>
    </div>
    
    <div class="boxs">
        <% @arts.each do |art| %>
        <div class="art_box">
            <div class="art_left">
                <div class="left_title">
                <%= art.title %>
                </div>
                <div class="left_grate">
                <%= art.grate %>年生の作品
                </div>
                <div class="left_content">
                <%= art.content %>
                </div>
                <div class="left_btn">
                    <div class="btn_edit">
                         <%= link_to "編集", edit_user_art_path(art.user_id, art.id) %>
                    </div>
                     
                    <div class="btn_delete">
                         <%= link_to "削除", user_art_path(art.user_id, art.id), method: :delete %>
                    </div>
                </div>
            </div>
            <div class="art_right">
                <%= image_tag art.image %>
            </div>
            
        </div>
        <% end %>
    </div>
    
</div>